on:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  release:
    name: 🚀 Publish to Marketplace
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 🛠️ Install dependencies
        run: npm install
      - name: 📦 Package .vsix
        run: npm run vsce:package
      - name: 📤 Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: formula-editor-${{github.sha}}
          path: formula-editor-*.vsix
      - name: 🚚 Publish to 🛒 Marketplace
        run: npm run vsce:publish
        env:
          VSCE_PAT: ${{secrets.VSCE_PAT}}
